/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-fixed": "#001a42",
        "secondary-fixed-dim": "#b7c8e1",
        "on-error": "#690005",
        "inverse-on-surface": "#2e3038",
        "on-tertiary-fixed-variant": "#005048",
        "tertiary-fixed-dim": "#4fdbc8",
        "surface": "#10131a",
        "secondary": "#b7c8e1",
        "tertiary-container": "#00a392",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        "tertiary-fixed": "#71f8e4",
        "surface-variant": "#32353c",
        "on-background": "#e1e2ec",
        "on-secondary-container": "#a9bad3",
        "primary-container": "#4d8eff",
        "secondary-container": "#3a4a5f",
        "surface-dim": "#10131a",
        "surface-tint": "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary": "#003731",
        "inverse-surface": "#e1e2ec",
        "on-tertiary-fixed": "#00201c",
        "on-secondary": "#213145",
        "surface-container-lowest": "#0b0e15",
        "error-container": "#93000a",
        "outline-variant": "#424754",
        "on-primary": "#002e6a",
        "primary": "#adc6ff",
        "background": "#10131a",
        "surface-container-high": "#272a31",
        "primary-fixed": "#d8e2ff",
        "surface-container": "#1d2027",
        "on-tertiary-container": "#00302a",
        "error": "#ffb4ab",
        "outline": "#8c909f",
        "on-secondary-fixed": "#0b1c30",
        "surface-bright": "#363941",
        "surface-container-low": "#191b23",
        "on-surface-variant": "#c2c6d6",
        "on-error-container": "#ffdad6",
        "tertiary": "#4fdbc8",
        "on-primary-fixed-variant": "#004395",
        "on-surface": "#e1e2ec",
        "surface-container-highest": "#32353c",
        "secondary-fixed": "#d3e4fe"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "xs": "4px",
        "margin": "40px",
        "unit": "4px",
        "xl": "32px",
        "lg": "24px",
        "sm": "8px",
        "gutter": "20px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "code-sm": ["monospace"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "code-sm": ["13px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
